### ISSUE TITLE
Default Layout displayed when layout containing content with future dated content is scheduled alongside valid layout.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo-dotnetclient#192]
Player Version:
R256

Issue:
Create and schedule a valid layout to show always. Now create a layout and add expiry times to the content for a date in the future. When you schedule the second layout to show always alongside the first layout, the default layout will instead display.

Notes:
- If the second layout is then removed from the schedule, the issue will persist until the player is restarted.
- Adding an additional valid layout to the schedule will also resolve the issue.

**Comment by dasgarner** [comment]
When we detect a layout failed to start, we remove it from the active schedule. We then check the count of active layouts to see if there are more than one. This count needs to be tested before we remove the failing Layout.

In addition, when we call NextLayout in Schedule, we try to get the prior layout to see if we need to update any state. However, if we have removed the prior layout from the schedule, this will fail with an index out of bounds. We probably need to refactor how NextLayout works so that we can do our tidy up before removing a failed layout from the schedule.
