### ISSUE TITLE
Question about XiboScreenTwo

### ISSUE THREAD

**Issue by jepe63** [xibosignage/xibo-dotnetclient#333]
Hi All, 
If this isn't allowed please inform me, can't find other place to put this
I installed two monitors on one PC and installed ScreenOne and Two software
Both software is working but two items
I can't put screentwo on monitor two
I don't kwow how it is possible to put different slides on screen two?
Thankx for the help

**Comment by dasgarner** [comment]
Hi and thank you for getting in touch. 

It looks like this might be a support request.

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
