### ISSUE TITLE
immediate update

### ISSUE THREAD

**Issue by odehalaa** [xibosignage/xibo-dotnetclient#338]
Hi,

I am currently using Xibo for digital signage and would like to know how to force an immediate update on the Xibo Player. Our content updates frequently, and it is crucial for us to ensure that the player reflects these changes as soon as they occur.

Could you please provide guidance on how to manually or programmatically force the Xibo Player to update immediately? If this functionality is not currently available, are there any workarounds or plans to include this feature in future releases?

Thank you for your assistance.

Best regards,

**Comment by dasgarner** [comment]
Hi and thank you for getting in touch. 

It looks like this might be a support request.

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
