### ISSUE TITLE
refresh

### ISSUE THREAD

**Issue by odehalaa** [xibosignage/xibo-dotnetclient#339]
Hi,

Kindly I used live HLS stream and working well but every minute I can see refresh screen on the player and can see background blue screen and back to normal , please how we can fix this issue ?

**Comment by dasgarner** [comment]
Hi and thank you for getting in touch. 

It looks like this might be a support request.

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
